kind: pipeline
name: linux

steps:
  - name: hi
    image: busybox
    environment:
      TEST:
        from_secret: test
      FROM_RONE:
        from_secret: FROM_DRONE
    commands:
      - env | grep -v ^DRONE
      - echo hello world
